name: test2

on:
  workflow_dispatch:

jobs:
  setup:
    name: test2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: hell world
        run: echo "test2"

      - name: Get associated PR
        id: pull_request_number
        run: |
          PR_NUMBER=$(gh pr list --head ${{ github.ref_name }} --json number --jq '.[0].number')
          echo "pull_request_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: step1
        if: steps.pull_request_number.outputs.pull_request_number != ''
        run: |
          echo "notEmpty"

      - name: step2
        if: steps.pull_request_number.outputs.pull_request_number == ''
        run: |
          echo "empty"
